config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :hellos


  namespace :dashboard do
    resources :get_emails_rules
    resources :things
  end
end

app/models/get_emails_rule.rb
class GetEmailsRule < ApplicationRecord
end

app/controllers/dashboard/get_emails_rules_controller.rb
class Dashboard::GetEmailsRulesController < ApplicationController
  before_action :authenticate_user!
  before_action :load_get_emails_rule, only: [:show, :edit, :update, :destroy]


  

  def load_get_emails_rule
    @get_emails_rule = current_user.get_emails_rules.find(params[:id])
  end

  def index
    @get_emails_rules = current_user.get_emails_rules.page(params[:page])

    respond_to do |format|
      format.js
    end
  end

  def new
    @get_emails_rule = GetEmailsRule.new(user: current_user)
    respond_to do |format|
      format.js
    end
  end

  def create
    @get_emails_rule = GetEmailsRule.create(get_emails_rule_params.merge!(user: current_user))
    respond_to do |format|
      if @get_emails_rule.save
        format.js
      else
        flash[:alert] = "Oops, your get_emails_rule could not be saved."
        format.js
      end
    end
  end

  def show
    respond_to do |format|
      format.html
    end
  end

  def edit

    respond_to do |format|
      format.js
    end
  end

  def update

    respond_to do |format|
      if !@get_emails_rule.save
        flash[:alert] = "Get Emails Rule could not be saved"
      end
      format.js {}
    end
  end

  def destroy
    respond_to do |format|
      begin
        @get_emails_rule.destroy
      rescue StandardError => e
        flash[:alert] = "Get Emails Rule could not be deleted"
      end
      format.js {}
    end
  end

  def get_emails_rule_params
    params.require(:get_emails_rule).permit( [:abc, :def, :ghi, :something_at, :something_color] )
  end

  def default_colspan
    5
  end

  def namespace
    
      "dashboard/"
    
  end


  def common_scope
    @nested_args
  end

end

app/controllers/dashboard/things_controller.rb
class Dashboard::ThingsController < ApplicationController

  before_action :authenticate_user!



  before_action :load_thing, only: [:show, :edit, :update, :destroy]


  

  def load_thing
    @thing = current_user.things.find(params[:id])
  end

  def index
    @things = current_user.things.page(params[:page])

    respond_to do |format|
      format.js
      format.html {render 'all.haml'}
    end
  end

  def new
    @thing = Thing.new(user: current_user)
    respond_to do |format|
      format.js
    end
  end

  def create
    @thing = Thing.create(thing_params.merge!(user: current_user))
    respond_to do |format|
      if @thing.save
        format.js
      else
        flash[:alert] = "Oops, your thing could not be saved."
        format.js
      end
    end
  end

  def show
    respond_to do |format|
      format.html
    end
  end

  def edit
    respond_to do |format|
      format.js
    end
  end

  def update
    respond_to do |format|
      if !@thing.update(thing_params)
        flash[:alert] = "Thing could not be saved"
      end
      format.js {}
    end
  end

  def destroy
    respond_to do |format|
      begin
        @thing.destroy
      rescue StandardError => e
        flash[:alert] = "Thing could not be deleted"
      end
      format.js {}
    end
  end

  def thing_params
    params.require(:thing).permit( [:a, :b, :c_at, :user_id] )
  end

  def default_colspan
    4
  end

  def namespace
    
      "dashboard/"
    
  end


  def common_scope
    @nested_args
  end

end

app/controllers/get_emails_rules_controller.rb
class GetEmailsRuleControllerController < ApplicationController

 
  before_action :load_get_emails_hook 
  before_action :load_get_emails_rule, only: [:show, :edit, :update, :destroy]


   
      
  def load_get_emails_hook
    @get_emails_hook = current_account.get_emails_hooks.find(params[:get_emails_hook_id])
  end 

  def load_get_emails_rule
    @get_emails_rule = @get_emails_hook.get_emails_rules.find(params[:id])
  end

  def index
    @get_emails_rules = @get_emails_hook.get_emails_rules
                            .where(GetEmailsRule.arel_table[:email].matches("%#{@__general_string}%"))
                            .page(params[:page])

    respond_to do |format|
      format.js
      # format.html {render 'dashboard/dashboard/all_get_emails_rules.haml'}
    end
  end

  def new
    @get_emails_rule = GetEmailsRule.new(account: current_account)
    respond_to do |format|
      format.js
    end
  end

  def create
    @get_emails_rule = GetEmailsRule.create(get_emails_rule_params.merge!(account: current_account))
    respond_to do |format|
      if @get_emails_rule.save
        format.js
      else
        flash[:alert] = "Oops, your get_emails_rule could not be saved."
        format.js
      end
    end
  end

  def show
    respond_to do |format|
      format.html
    end
  end

  def edit

    respond_to do |format|
      format.js
    end
  end

  def update

    respond_to do |format|
      if !@get_emails_rule.save
        flash[:alert] = "Get Emails Rule could not be saved"
      end
      format.js {}
    end
  end

  def destroy
    respond_to do |format|
      begin
        @get_emails_rule.destroy
      rescue StandardError => e
        flash[:alert] = "Get Emails Rule could not be deleted"
      end
      format.js {}
    end
  end

  def get_emails_rule_params
    params.require(:get_emails_rule).permit( [:abc, :def, :ghi, :something_at, :something_color] )
  end

  def default_colspan
    5
  end
end

app/views/dashboard/get_emails_rules/_edit.haml
= render partial: "common/common_edit_form", locals: {singular: 'get_emails_rule', object: get_emails_rule, url: dashboard_get_emails_rule_path(, @get_emails_rule), colspan: colspan}

app/views/dashboard/get_emails_rules/_list.haml
= link_to "New get emails rule", new_dashboard_get_emails_rule_path(), disable_with: "Loading...", remote: true, class: "new-get_emails_rule-button btn btn-primary pull-right"

.clearfix
.new-get_emails_rule-form{style: "display: none; position: relative;"}



%table.table.table-striped.get_emails_rule-table
  %thead
    %tr
      %th{:scope => "col"} Abc      %th{:scope => "col"} Def      %th{:scope => "col"} Ghi      %th{:scope => "col"} Something at      %th{:scope => "col"} Something color



  %tbody
    - if get_emails_rules.empty?
      None
    - get_emails_rules.each do |get_emails_rule|
      = render partial: 'dashboard/get_emails_rule/line', locals: {get_emails_rule: get_emails_rule,  }

app/views/dashboard/get_emails_rules/_new.haml
= render partial: "common/common_new_form", locals: {singular: 'get_emails_rule', plural: "get_emails_rules", object: @get_emails_rule, url: new_dashboard_get_emails_rule_path()}

app/views/dashboard/get_emails_rules/create.js.erb
<%= render partial: 'common/common_create', locals: {object: @get_emails_rule, singular: "get_emails_rule", plural: "get_emails_rules"} %>

app/views/dashboard/get_emails_rules/destroy.js.erb
<%= render partial: 'common/common_destroy', locals: {object: @get_emails_rule, singular: "get_emails_rule", plural: "get_emails_rules", all_objects: current_user..get_emails_rules} %>

app/views/dashboard/get_emails_rules/edit.js.erb
<%= render partial: 'common/common_edit', locals: {object: @get_emails_rule, singular: "get_emails_rule", plural: "get_emails_rules", url: dashboard_get_emails_rule_path(, @get_emails_rule)} %>

app/views/dashboard/get_emails_rules/index.js.erb
<%= render partial: 'common/common_index', locals: {objects: @get_emails_rules, singular: "get_emails_rule", plural: "get_emails_rules"} %>

app/views/dashboard/get_emails_rules/new.js.erb
<%= render partial: 'common/common_new', locals: {object: @get_emails_rule, singular: "get_emails_rule", plural: "get_emails_rules"} %>

app/views/dashboard/get_emails_rules/update.js.erb
<%= render partial: 'common/common_update', locals: {object: @get_emails_rule, singular: "get_emails_rule",
plural: "get_emails_rules",
 url: dashboard_get_emails_rule_path(, @get_emails_rule),
 pass_through_locals: {
  
}} %>