config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :hellos


  namespace :dashboard do
    resources :get_emails_rules
    resources :things
  end
end

app/models/thing.rb
class Thing < ApplicationRecord
  belongs_to :user
end

app/controllers/dashboard/things_controller.rb
class Dashboard::ThingsController < ApplicationController

  before_action :authenticate_user!



  before_action :load_thing, only: [:show, :edit, :update, :destroy]


  

  def load_thing
    @thing = current_user.things.find(params[:id])
  end

  def index
    @things = current_user.things.page(params[:page])

    respond_to do |format|
      format.js
      format.html {render 'all.haml'}
    end
  end

  def new
    @thing = Thing.new(user: current_user)
    respond_to do |format|
      format.js
    end
  end

  def create
    @thing = Thing.create(thing_params.merge!(user: current_user))
    respond_to do |format|
      if @thing.save
        format.js
      else
        flash[:alert] = "Oops, your thing could not be saved."
        format.js
      end
    end
  end

  def show
    respond_to do |format|
      format.html
    end
  end

  def edit
    respond_to do |format|
      format.js
    end
  end

  def update
    respond_to do |format|
      if !@thing.update(thing_params)
        flash[:alert] = "Thing could not be saved"
      end
      format.js {}
    end
  end

  def destroy
    respond_to do |format|
      begin
        @thing.destroy
      rescue StandardError => e
        flash[:alert] = "Thing could not be deleted"
      end
      format.js {}
    end
  end

  def thing_params
    params.require(:thing).permit( [:a, :b, :c_at, :user_id] )
  end

  def default_colspan
    4
  end

  def namespace
    
      "dashboard/"
    
  end


  def common_scope
    @nested_args
  end

end

app/controllers/things_controller.rb
class ThingsController < ApplicationController

  before_action :authenticate_user!



  before_action :load_thing, only: [:show, :edit, :update, :destroy]


  

  def load_thing
    @thing = current_user.things.find(params[:id])
  end

  def index
    @things = current_user.things.page(params[:page])

    respond_to do |format|
      format.js
    end
  end

  def new
    @thing = Thing.new(user: current_user)
    respond_to do |format|
      format.js
    end
  end

  def create
    @thing = Thing.create(thing_params.merge!(user: current_user))
    respond_to do |format|
      if @thing.save
        format.js
      else
        flash[:alert] = "Oops, your thing could not be saved."
        format.js
      end
    end
  end

  def show
    respond_to do |format|
      format.html
    end
  end

  def edit
    respond_to do |format|
      format.js
    end
  end

  def update
    respond_to do |format|
      if !@thing.save
        flash[:alert] = "Thing could not be saved"
      end
      format.js {}
    end
  end

  def destroy
    respond_to do |format|
      begin
        @thing.destroy
      rescue StandardError => e
        flash[:alert] = "Thing could not be deleted"
      end
      format.js {}
    end
  end

  def thing_params
    params.require(:thing).permit( [:a, :b, :c_at, :user_id] )
  end

  def default_colspan
    4
  end

  def namespace
    
      ""
    
  end


  def common_scope
    @nested_args
  end

end

app/views/things/_edit.haml
= render partial: "common/common_edit_form", locals: {singular: 'thing', object: thing, url: thing_path(@thing), colspan: colspan}

app/views/things/_form.haml
.row
  .form-group.col-md-4
    = f.text_field :a, size: 40, class: 'form-control'
    %label.form-text
      A

.row
  .form-group.col-md-4
    = f.text_field :b, class: 'form-control', size: 4, type: 'number'
    %label.form-text
      B

.row
  .form-group.col-md-4
    = f.text_field :c_at, class: 'form-control', type: 'datetime-local'
    %label.form-text
      C at

.row
  .form-group.col-md-4
    = f.collection_select(:user_id, User.all, :id, :to_label, {:prompt => true}, class: 'form-control')
    %label.small.form-text.text-muted
      User

app/views/things/_list.haml
= link_to "New thing", new_thing_path(), disable_with: "Loading...", remote: true, class: "new-thing-button btn btn-primary pull-right"

.clearfix
.new-thing-form{style: "display: none; position: relative;"}



%table.table.table-striped.thing-table
  %thead
    %tr
      %th{:scope => "col"} A      %th{:scope => "col"} B      %th{:scope => "col"} C at      %th{:scope => "col"} User



  %tbody
    - if things.empty?
      None
    - things.each do |thing|
      = render partial: 'things/line', locals: {thing: thing,  }

app/views/things/_new.haml
= render partial: "common/common_new_form", locals: {singular: 'thing', plural: "things", object: @thing, url: things_path()}

app/views/things/create.js.erb
<%= render partial: 'common/common_create', locals: {object: @thing, singular: "thing", plural: "things"} %>

app/views/things/destroy.js.erb
<%= render partial: 'common/common_destroy', locals: {object: @thing, singular: "thing", plural: "things", all_objects: current_user.things} %>

app/views/things/edit.js.erb
<%= render partial: 'common/common_edit', locals: {object: @thing, singular: "thing", plural: "things", url: thing_path(@thing)} %>

app/views/things/index.js.erb
<%= render partial: 'common/common_index', locals: {objects: @things, singular: "thing", plural: "things"} %>

app/views/things/new.js.erb
<%= render partial: 'common/common_new', locals: {object: @thing, singular: "thing", plural: "things"} %>

app/views/things/update.js.erb
<%= render partial: 'common/common_update', locals: {object: @thing, singular: "thing",
plural: "things",
 url: thing_path(@thing),
 pass_through_locals: {
  
}} %>