config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :hellos


  namespace :dashboard do
    resources :get_emails_rules
    resources :things
  end
end

app/models/thing.rb
class Thing < ApplicationRecord
  belongs_to :user
end

app/controllers/dashboard/get_emails_rules_controller.rb
class Dashboard::GetEmailsRulesController < ApplicationController
  before_action :authenticate_user!
  before_action :load_get_emails_rule, only: [:show, :edit, :update, :destroy]


  

  def load_get_emails_rule
    @get_emails_rule = current_user.get_emails_rules.find(params[:id])
  end

  def index
    @get_emails_rules = current_user.get_emails_rules.page(params[:page])

    respond_to do |format|
      format.js
    end
  end

  def new
    @get_emails_rule = GetEmailsRule.new(user: current_user)
    respond_to do |format|
      format.js
    end
  end

  def create
    @get_emails_rule = GetEmailsRule.create(get_emails_rule_params.merge!(user: current_user))
    respond_to do |format|
      if @get_emails_rule.save
        format.js
      else
        flash[:alert] = "Oops, your get_emails_rule could not be saved."
        format.js
      end
    end
  end

  def show
    respond_to do |format|
      format.html
    end
  end

  def edit

    respond_to do |format|
      format.js
    end
  end

  def update

    respond_to do |format|
      if !@get_emails_rule.save
        flash[:alert] = "Get Emails Rule could not be saved"
      end
      format.js {}
    end
  end

  def destroy
    respond_to do |format|
      begin
        @get_emails_rule.destroy
      rescue StandardError => e
        flash[:alert] = "Get Emails Rule could not be deleted"
      end
      format.js {}
    end
  end

  def get_emails_rule_params
    params.require(:get_emails_rule).permit( [:abc, :def, :ghi, :something_at, :something_color] )
  end

  def default_colspan
    5
  end

  def namespace
    
      "dashboard/"
    
  end


  def common_scope
    @nested_args
  end

end

app/controllers/dashboard/things_controller.rb
class Dashboard::ThingsController < ApplicationController

  before_action :authenticate_user!



  before_action :load_thing, only: [:show, :edit, :update, :destroy]


  

  def load_thing
    @thing = current_user.things.find(params[:id])
  end

  def index
    @things = current_user.things.page(params[:page])

    respond_to do |format|
      format.js
      format.html {render 'all.haml'}
    end
  end

  def new
    @thing = Thing.new(user: current_user)
    respond_to do |format|
      format.js
    end
  end

  def create
    @thing = Thing.create(thing_params.merge!(user: current_user))
    respond_to do |format|
      if @thing.save
        format.js
      else
        flash[:alert] = "Oops, your thing could not be saved."
        format.js
      end
    end
  end

  def show
    respond_to do |format|
      format.html
    end
  end

  def edit
    respond_to do |format|
      format.js
    end
  end

  def update
    respond_to do |format|
      if !@thing.update(thing_params)
        flash[:alert] = "Thing could not be saved"
      end
      format.js {}
    end
  end

  def destroy
    respond_to do |format|
      begin
        @thing.destroy
      rescue StandardError => e
        flash[:alert] = "Thing could not be deleted"
      end
      format.js {}
    end
  end

  def thing_params
    params.require(:thing).permit( [:a, :b, :c_at, :user_id] )
  end

  def default_colspan
    4
  end

  def namespace
    
      "dashboard/"
    
  end


  def common_scope
    @nested_args
  end

end

app/controllers/things_controller.rb
class ThingsController < ApplicationController

  before_action :authenticate_user!



  before_action :load_thing, only: [:show, :edit, :update, :destroy]


  

  def load_thing
    @thing = current_user.things.find(params[:id])
  end

  def index
    @things = current_user.things.page(params[:page])

    respond_to do |format|
      format.js
    end
  end

  def new
    @thing = Thing.new(user: current_user)
    respond_to do |format|
      format.js
    end
  end

  def create
    @thing = Thing.create(thing_params.merge!(user: current_user))
    respond_to do |format|
      if @thing.save
        format.js
      else
        flash[:alert] = "Oops, your thing could not be saved."
        format.js
      end
    end
  end

  def show
    respond_to do |format|
      format.html
    end
  end

  def edit
    respond_to do |format|
      format.js
    end
  end

  def update
    respond_to do |format|
      if !@thing.save
        flash[:alert] = "Thing could not be saved"
      end
      format.js {}
    end
  end

  def destroy
    respond_to do |format|
      begin
        @thing.destroy
      rescue StandardError => e
        flash[:alert] = "Thing could not be deleted"
      end
      format.js {}
    end
  end

  def thing_params
    params.require(:thing).permit( [:a, :b, :c_at, :user_id] )
  end

  def default_colspan
    4
  end

  def namespace
    
      ""
    
  end


  def common_scope
    @nested_args
  end

end

app/views/dashboard/things/_edit.haml
= render partial: "common/common_edit_form", locals: {singular: 'thing', object: thing, url: dashboard_thing_path(@thing), colspan: colspan}

app/views/dashboard/things/_line.haml
%tr{'data-id': thing.id, 'data-edit': 'false'}
  %td
    = thing.a
  %td
    = thing.b
  %td
    = thing.c_at
  %td
    = thing.user.to_label
  %td
    = link_to "Edit <i class='fa fa-1x fa-list-alt'></i>".html_safe, edit_dashboard_thing_path(thing), remote: true , disable_with: "Loading...", class: "edit-thing-button btn btn-primary pull-right "

app/views/dashboard/things/_list.haml
= link_to "New thing", new_dashboard_thing_path(), disable_with: "Loading...", remote: true, class: "new-thing-button btn btn-primary pull-right"

.clearfix
.new-thing-form{style: "display: none; position: relative;"}



%table.table.table-striped.thing-table
  %thead
    %tr
      %th{:scope => "col"} A      %th{:scope => "col"} B      %th{:scope => "col"} C at      %th{:scope => "col"} User



  %tbody
    - if things.empty?
      None
    - things.each do |thing|
      = render partial: 'dashboard/thing/line', locals: {thing: thing,  }

app/views/dashboard/things/_new.haml
= render partial: "common/common_new_form", locals: {singular: 'thing', plural: "things", object: @thing, url: dashboard_things_path()}

app/views/dashboard/things/all.haml
.container-fluid
  .row
    .col-md-12
      = render partial: "dashboard/things/list", locals: {things: current_user.things.order("created_at DESC").page(1)}

app/views/dashboard/things/edit.js.erb
<%= render partial: 'common/common_edit', locals: {object: @thing, singular: "thing", plural: "things", url: dashboard_thing_path(@thing)} %>

app/views/dashboard/things/update.js.erb
<%= render partial: 'common/common_update', locals: {object: @thing, singular: "thing",
plural: "things",
 url: dashboard_thing_path(@thing),
 pass_through_locals: {
  
}} %>